### ISSUE TITLE
Fix namelist settings for aquaplanet runs

### ISSUE THREAD

**Issue by quantheory** [CESM-Development/cime#108]
From Bugzilla:

http://bugs.cgd.ucar.edu/show_bug.cgi?id=2133

The description in the report is not totally right (e.g. I'm not sure that cpl.buildnml is the right place for these changes), but the gist is that for aquaplanet runs:
1. We need to use fixed orbital parameters, all set to 0.
2. The setting of `aqua_planet_sst`/`sst_option` needs to work.
3. `CCSM_CO2_PPMV` needs to be set to 348.

**Comment by jedwards4b** [comment]
I think that this may be resolved by #64

On Tue, Aug 4, 2015 at 1:31 PM, Sean Patrick Santos <
notifications@github.com> wrote:

> From Bugzilla:
> 
> http://bugs.cgd.ucar.edu/show_bug.cgi?id=2133
> 
> The description in the report is not totally right, but the gist is that
> for aquaplanet runs:
> 1. We need to use fixed orbital parameters, all set to 0.
> 2. The setting of aqua_planet_sst/sst_option needs to work.
> 3. CCSM_CO2_PPMV needs to be set to 348.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CESM-Development/cime/issues/108.

## 

Jim Edwards

CESM Software Engineer
National Center for Atmospheric Research
Boulder, CO

**Comment by quantheory** [comment]
No, #64 is actually about what effect the namelist parameters have after being read in. This bug has more to do with the fact that the namelists are not set in the expected way for aquaplanet runs in the first place.

**Comment by brian-eaton** [comment]
Sean is correct.  #64 is orthogonal to this.
1.  When aquaplanet runs from CAM standalone CAM is responsible for setting the orbital parameters which it does via its use case file.  When running from CESM scripts whoever is responsible for the seq_infodata_inparm group needs to do this.
2. In CAM standalone the configure script adds the appropriate filepaths to build the ocean component that specifies the aquaplanet SSTs.  From CESM scripts presumably some ocn component script needs to build a lib with the files in cam/src/utils/cam_aqua/ and cam/src/utils/cam_aqua/cpl/.
3. The CAM component is solely responsible for the CO2 value which it sets via its use case file.  I see no reason why CCSM_CO2_PPMV needs to be set at all.

**Comment by quantheory** [comment]
Finally noticed this comment. Currently, `CCSM_CO2_PPMV` always needs to be set in CIME, and moreover it needs to be set to the correct value, because it is put in through the `-infile` argument, which takes precedence over the `-use_case` file.

More generally, CIME is the dictator not only over the coupler settings, but for `dtime`, `start_ymd`, and `co2vmr`. Any defaults for these set in CAM use cases will apply only for standalone builds of CAM.

**Comment by brian-eaton** [comment]
This is a very old feature of the scripts which should be refactored.  For many (most?) compsets a single co2vmr value is insufficient information and CAM is ignoring this setting and getting values from datasets.  It would be better if CCSM_CO2_PPMV were only set when it is actually needed.  To be honest I'm not sure exactly when it is needed.  Certainly when CAM is an active component the other components should be getting the surface layer value of CO2 from CAM via the coupler.

**Comment by quantheory** [comment]
Granted. Looking at this, I think that CCSM_CO2_PPMV should be removed entirely, and I'll open a separate issue for that.

**Comment by ekluzek** [comment]
The current situation is bad with CCSM_CO2_PPMV, since it sometimes just
causes confusion. And it seems better that when CAM is being used, that we
just do what CAM tells us to do. Also note that WACCM compsets, set it to a
very small value with the idea that the model will abort with bad behavior
if it's actually used instead of something from inside of CAM. But, this
doesn't guarantee that it will abort, as we found out with the isotope
branch.

However, what about when CAM is not part of the equation and datm or satm
is being used? datm can now pass CO2, so that can probably be configured
correctly. But, are there any compsets that use satm, that also need to set
surface layer CO2?

_Erik Kluzek, (CGD at NCAR)_

_National Center for Atmospheric Research_

*Boulder CO, *

_(off) (303)497-1326 (fax) (303)497-1348_

_(skype) ekluzek    (cell) (303)859-0183_

_Pronouns: he/his/him_

_------------------ Home page ------------------------_
- ```
       http://www.cgd.ucar.edu/~erik <http://www.cgd.ucar.edu/~erik>*
  ```
- ```
       https://staff.ucar.edu/users/erik
  ```
  
  https://staff.ucar.edu/users/erik*

_!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!_

**Comment by quantheory** [comment]
I've moved the CO2 refactoring discussion to #121, so as not to mix it up too much with the aquaplanet issues here.

Aside from the S compset, which is presumably just for testing, only the TG compsets use SATM, so I CC'ed Bill on the other bug. But it looks to me like `CCSM_CO2_PPMV` is not used by DLND or CISM for those compsets, so this is probably a non-issue for SATM cases.

**Comment by billsacks** [comment]
@brian-eaton or others: What is the status of this? If it's still an issue, we should move it to esmci; if so, does it need to be fixed for cesm2? If it's fixed, we should close it.
