### ISSUE TITLE
CIME-ization of CMake (mostly unit) tests

### ISSUE THREAD

**Issue by quantheory** [CESM-Development/cime#12]
I will have a PR for most of this pretty soon, but I just wanted to put up a list of items to resolve.
1. Put a top-level `CMakeLists.txt` in CIME for building the existing unit tests. Should be simple as long as we don't have problems with name collisions.
2. Replace CESM labels with CIME. Mostly this is about directory structure, i.e. doing as much as possible relative to the root directory of CIME rather than up one directory in the host model. This shouldn't be much of an issue either, since I am already running tests in "standalone" CIME without CESM.
3. Switch the unit testing scripts to use `machines/configure`? Might be a separate PR, because it's kind of orthogonal to the rest of this, and there's the complication that the unit tests have to be able to run on unsupported machines like people's laptops, assuming that they have a basic *nix environment with a supported compiler. AFAIK, this is not a situation that `configure` has had to handle out-of-the-box.
   
   **Edit:** We should also XML-ify the various Depends files in machines (e.g. `Depends.intel`). This is necessary for the unit tests to be run with the same options as the system build uses.

Integration with other changes:
- @bandre-ucar's `Makefile` has to call this (the easiest thing is for it to just use `run_tests.py`, but we need a little finesse to pick a reasonable default compiler for a given machine, or to run with multiple compilers).
- ~~Running the test for `gen_domains` that @ekluzek is going to move into CIME. The test could be called from Ben's `Makefile`, but I think that it's easier to see what's going on if all the tests that are not CIME/CESM system tests run through a single round of CTest. That way you get one summary for the whole lot of them. (However, I'm assuming that the `gen_domains` test is fast enough to throw in with the unit tests without causing problems. If it takes more than a second or two to run, not including build time, we need a different solution.)~~ **Edit:** Never mind, see discussion below.

**Comment by quantheory** [comment]
CC @jedwards4b, while I'm at it.

**Comment by quantheory** [comment]
Oh, and although it's not urgently needed to run PIO tests from here, since PIO can be built and tested on its own, it wouldn't hurt to add the ability to run tests for the PIO version currently in CIME.

**Comment by jedwards4b** [comment]
I was copied the first time...

The machines/configure should be able to handle the generic case, try it
anyway.

It should be easy to enable PIO tests, it's CMakeLists.xml just needs an
additional argument or two.

On Mon, May 18, 2015 at 2:23 PM, Sean Patrick Santos <
notifications@github.com> wrote:

> CC @jedwards4b https://github.com/jedwards4b, while I'm at it.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CESM-Development/cime/issues/12#issuecomment-103199003
> .

## 

Jim Edwards

CESM Software Engineer
National Center for Atmospheric Research
Boulder, CO

**Comment by quantheory** [comment]
Yeah, I forget that we have that subscription set up so that some people get notified for every new issue.

I'll try to get as much as I can done at once; I'll let you know if there are any issues relevant to you.

**Comment by billsacks** [comment]
@quantheory and @ekluzek : Regarding gen_domain: (This should probably be moved to its own issue, but I'm commenting here since you mentioned it.) My initial reaction is that this test should not be part of the unit test suite, at least not as it is currently written. This is for (at least) three reasons:

(1) It requires pointing to a checkout of a baseline tag that you want to compare against - something that is not needed for other unit tests.

(2) It currently points to a mapping file in the inputdata repository. Currently this is hard-coded for yellowstone paths. But regardless, you would need to have this mapping file on your local machine if you want to test locally.

(3) I suspect (but haven't tested yet) that it takes significantly longer to run than all of the other (current) unit tests combined. This is partly because it uses production resolutions (like ne30).

These issues could be addressed by:

(2) & (3): using a very small mapping file that we create solely for the purpose of testing gen_domain

(1): Storing the baseline (expected result) in the repository. This is feasible if we use a very small domain - I'm thinking just a few grid cells.

That said, I'm not sure if that's the right approach here. It may be better to think of the gen_domain test as being more similar to a system test rather than a unit test.

**Comment by ekluzek** [comment]
I think we should think of gen_domain as a system test of a particular
tool. In the longer run we probably want to have a set of tools system
tests that run on all of the tools under cime/tools. The baseline result
should probably be handled similar to the main cime/scripts/create_test
with generate and compare options and the result stored under ccsm_baseline.

It doesn't take a horrible amount of time, but Bill is probably right that
it's likely to be longer than the other unit tests. It still think it's
fast enough that testing at production resolutions is OK. But, that's IMHO.

_Erik Kluzek, (CGD at NCAR)_

_National Center for Atmospheric Research_

*Boulder CO, *

_(off) (303)497-1326 (fax) (303)497-1348_

_(skype) ekluzek    (cell) (303)859-0183_

_Pronouns: he/his/him_

_------------------ Home page ------------------------_
- ```
       http://www.cgd.ucar.edu/~erik <http://www.cgd.ucar.edu/~erik>*
  ```
- ```
       https://staff.ucar.edu/users/erik
  ```
  
  https://staff.ucar.edu/users/erik*

_!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!_

**Comment by jedwards4b** [comment]
Closing this issue in, it is still referenced in esmci#787 and can be found from there if needed.
