### ISSUE TITLE
model cost in timing file 

### ISSUE THREAD

**Issue by jedwards4b** [CESM-Development/cime#158]
We need to assure that the model cost estimate in the timing file is correct for all supported machines.

**Comment by mnlevy1981** [comment]
As of cime4.2.0, it's not right on yellowstone -- the "pe count for cost estimate" is listed as the number of tasks \* number of threads and I think we want something a little more complicated to account for hyperthreading and the fact that we are being charged for 16 pes per node even if we are only using 15 MPI tasks on it. For example,

```
  component       comp_pes    root_pe   tasks  x threads instances (stride) 
  ---------        ------     -------   ------   ------  ---------  ------  
  cpl = cpl        30          0        15     x 2       1      (1     ) 
  glc = sglc       30          0        15     x 2       1      (1     ) 
  wav = swav       30          0        15     x 2       1      (1     ) 
  lnd = slnd       30          0        15     x 2       1      (1     ) 
  rof = drof       30          0        15     x 2       1      (1     ) 
  ice = cice       180         15       90     x 2       1      (1     ) 
  atm = datm       30          0        15     x 2       1      (1     ) 
  ocn = pop        180         105      90     x 2       1      (1     ) 

  total pes active           : 390 
  pes per node               : 15 
  pe count for cost estimate : 390 
```

I am using 13 yellowstone nodes, so my pe count for cost estimate should be 13*16 = 208 rather than the reported 390.

**Comment by jedwards4b** [comment]
Issue #262 elaborates

**Comment by jedwards4b** [comment]
Fixed in cime5
