### ISSUE TITLE
For create_newcase and case_setup, move some prints into an 'if verbose' conditional

### ISSUE THREAD

**Issue by billsacks** [CESM-Development/cime#159]
I feel like the pendulum has been swinging to more verbosity of create_newcase and case_setup -- too much, in my opinion.

Jim's suggestion, which I agree with, is that more of the prints in create_newcase should be moved into 'if verbose' conditionals, and a verbose flag should be added to case_setup, with most or all prints moved in there.

My personal preference would be to have little or no information output by default... perhaps just a single line along the lines of "$CASENAME successfully created". Then it would be clear that any extra output signals a problem.

**Comment by billsacks** [comment]
cc @jedwards4b @mvertens @sholly

**Comment by bandre-ucar** [comment]
I'd actually prefer some canned output subroutines in perl5lib instead of
bare print statements. Then it would be easy to create a pseudo progress
bar with careful newlines and ensure grep-ability of results from log
files. Something like:

verbose_message($verbose_message);

sub verbose_message {
    if ($verbose || $debug) {
      printf('$verbose_message \n');
    } else {
      printf('.');
    }
}

if ($some_error_condition) {
  error_message($some_error_message);
}

sub error_message {
    printf('\nERROR: $some_error_message \n');
    die;
}

# last line of a script:

finalize($some_script_name, $CASENAME);

sub finalize {
    print('\n $some_script_name for $casename completed successfully.\n")
}

**Comment by billsacks** [comment]
I really like @bandre-ucar 's idea.

**Comment by jedwards4b** [comment]
Please feel free to create a Messages.pm module and implement this.

On Tue, Sep 15, 2015 at 12:02 PM, Bill Sacks notifications@github.com
wrote:

> I really like @bandre-ucar https://github.com/bandre-ucar 's idea.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CESM-Development/cime/issues/159#issuecomment-140484525
> .

## 

Jim Edwards

CESM Software Engineer
National Center for Atmospheric Research
Boulder, CO

**Comment by jedwards4b** [comment]
Implemented using Log::Log4perl  
Scripts now take option -loglevel which can be set to 
DEBUG INFO WARN ERROR FATAL     (most to least verbose)
default : INFO
