### ISSUE TITLE
Speed up build and submit scripts

### ISSUE THREAD

**Issue by billsacks** [CESM-Development/cime#229]
I'd like to see the build script (specifically, the stuff that happens before the build itself begins) and the submit script sped up. From cime4.0.1, the submit script takes 16 seconds for an I compset on yellowstone.

This could be done by:
- removing some of this stuff: do we really need to rebuild component namelists all the time?
- rearranging some things: when I fix a compilation error and rebuild, it's annoying to have to wait while the component namelists get rebuilt before I can see if my compilation will now succeed
- speeding up individual steps: it's unclear to me why this takes so long... can we do some profiling to figure it out?

Each time this happens, the time lost isn't huge. But aggregated over all the times it occurs, it builds up.

**Comment by rljacob** [comment]
We were wondering the same thing.  Tagging @jgfouca

**Comment by jedwards4b** [comment]
So I have been working on a branch to address this issue, it's been a low
priority issue so progress is slow.   But I recognize that there could be a
lot more reuse of code as well as hierarchy and OO design.  I am working to
integrate the scripts so that a given task is done in one place.
Currently one expensive item is that xmlquery and xmlchange read or write
an entire file each time they are accessed.  At one point I attempted to
fix the xmlquery / xmlchange issue without addressing the general hierarchy
of
the code, I realised that was the wrong approach and decided to take it all
on at once.

  A well designed case object would only need to read that information once
currently we are doing it dozens of times for each build.

What i am working on is a hierarchy with general xml file interfaces at the
lowest level and interfaces to each individual xml file at a layer above
that.  Then a case layer above that that would interface with each of the
xml layer files.    All of the current command line functionality would
remain the same but perl should call other perl via subroutine interfaces
so that we never need to go through the shell.

I have a minimally functional prototype in
https://github.com/jedwards4b/cime.git
branch perlOOrefactor  It's far from ready - so far I have more ideas than
code, but I would welcome discussion and feedback.

On Tue, Oct 13, 2015 at 5:57 PM, Robert Jacob notifications@github.com
wrote:

> We were wondering the same thing. Tagging @jgfouca
> https://github.com/jgfouca
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CESM-Development/cime/issues/229#issuecomment-147887480
> .

## 

Jim Edwards

CESM Software Engineer
National Center for Atmospheric Research
Boulder, CO

**Comment by rljacob** [comment]
Following up on the slow build:  I'd like to see the .build script just build object code and executables.  I think we need another script that does all the file moving and namelist making.  Then when you're debugging, you just have to execute the (slimmed down) build script and it should be nice and fast.

**Comment by quantheory** [comment]
I don't want to make an inappropriate generalization here, but my experience with standalone CAM builds, and my gut instinct is that building separate components in parallel would help a lot. E.g. building CAM in parallel with CLM, and with whatever other components. My recollection is that this had a 30%-40% effect on build time back in the day, but we would need to test again to see how things are now.

As Jim said, the main issue with scripts was use of XMLite, especially reading, parsing, and re-writing entire files, which was not only unsafe but inefficient.

@billsacks @rljacob I think that you may be overestimating the effect of namelist scripts (unless they are taking longer than I remember). These took >10 seconds a year ago, but I tried to tackle this; maybe if things are that bad, we should impose a hard limit of a few seconds for preview_namelists runs, since I really don't see why it should take longer, under any circumstances?

My recollection is that the main annoyance here is that the unit tests and system tests are separate, so that building the unit tests doesn't speed up system tests, and vice versa. (I admittedly am not in the loop about ACME's testing here.) That and batch system queue times, which as always are in the minutes-to-hours range, even when tests are on the order of seconds.

**Comment by billsacks** [comment]
Thanks, @jedwards4b for your work on this!

@quantheory : For this case on yellowstone (SMS_D_Ld3.f10_f10.I1850CLM45BGC.yellowstone_pgi.clm-interp_f19_crop), I just timed the buildnml scripts at about 8 seconds. I imagine a B compset would take longer. The rest of the 16 seconds is due to "checking the case" (which takes a few seconds), module loads (which are done twice), and finally the actual job submission.

**Comment by jgfouca** [comment]
I have updates to create_test (ACME's create test, not yet pushed) that will setup/build all your cases in parallel. This doesn't help the speed of a single case, but works great when you're doing a bunch of cases.

In my opinion, the right way to fix the builds is to transition the entire system to CMake.

**Comment by billsacks** [comment]
fixed in python
