### ISSUE TITLE
TaskMaker.pm 

### ISSUE THREAD

**Issue by jedwards4b** [CESM-Development/cime#262]
The computation of the total tasks for cost estimate is wrong.

An initial attempt to fix the problem indicated deeper flaws in this code.

We need to first understand what outputs from this module are actually used.
Second we need to determine the inputs necessary for each of these outputs.
Then rewrite the module.

**Comment by jedwards4b** [comment]
A workaround to compute the pes for cost estimate correctly:

After running case.setup:

./xmlchange TOTALPES=(total nodes used \* PES_PER_NODE)
 cp env_mach_pes.xml LockedFiles/env_mach_pes.xml.locked

build and run as usual.

**Comment by rljacob** [comment]
I think @jayeshkrishna has been looking at this too.

**Comment by jayeshkrishna** [comment]
The fix that we have for node layout on Titan might touch on this issue. Not sure if that is the fix but this might be a good time to integrate the change from ACME to the cime master. I will start working on it.

**Comment by apcraig** [comment]
There is an env variable called PES_PER_NODE.  If you look at the documentation, the purpose of that is "pes or cores per node for accounting purposes".  What you want to do is set that to 16 for yellowstone and then the "cost" should be associated with nodes*${PES_PER_NODE}.  That's exactly what that PES_PER_NODE is there for.  If it's being used for something else now, we need to fix that.  The MAX_TASKS_PER_NODE is what should be used to layout the tasks on the nodes and that variable is the thing that allows hyperthreading to be done.  This logic existed in the past, but must have been broken at some point.  On the latest cime trunk, the GetTiming file has this,

```
my $pecost = $xml{TOTALPES};
if ($xml{COST_PES} > 0) {
$pecost = $xml{COST_PES};
}
```

but it looks like COST_PES is no longer computed and set.  It just defaults to zero and that's why the cost is fouled up.

**Comment by jedwards4b** [comment]
TaskMaker was removed from cime5
