### ISSUE TITLE
create_test options

### ISSUE THREAD

**Issue by jedwards4b** [CESM-Development/cime#268]
The options to create test are confusing
options with -xml_ cannot be combined with -testname option
but the error if you do this is obtuse and difficult to understand

**Comment by bertinia** [comment]
In addition, if you want to use testmods, in order for them to be recognized, you need to specify the
testname option as follows:
./create_test -testname ERR_N2.f19_g16.B1850.yellowstone_intel.allactive-defaultio
rather than:
./create_test -testname ERR_N2.f19_g16.B1850.allactive-defaultio -mach yellowstone -compiler intel

**Comment by jedwards4b** [comment]
Fixed in cime5 although part of is resolved through improved usage arguments
