### ISSUE TITLE
wallclock time and other job script parameters

### ISSUE THREAD

**Issue by jedwards4b** [CESM-Development/cime#27]
I would like a way to quickly edit the wallclock time or submit queue for a particular job.   I think currently these variables are read from the machines directory each time.   They should be copied to env_run.xml so that they can be user edited.

**Comment by jedwards4b** [comment]
In particular it would be good if tests were tuned to walltime suitable for that particular test on that machine.

**Comment by quantheory** [comment]
I agree. However, I suppose that means that the run script header has to be regenerated every time (or we have to put the clock time and queue into `qsub`/`bsub`/whatever arguments instead of the header). Also editing that script will have no effect because changes will be overridden. If we do this, we should probably also move the run script to Buildconf or something, so that it doesn't look like one of the main case files that you're supposed to edit or submit directly by hand.

**Comment by jedwards4b** [comment]
The wallclock time for tests are set in the test script which is different than the run script, I think that this is the case on all machines except mira.

**Comment by jedwards4b** [comment]
Fixed - yeah
