### ISSUE TITLE
inabilty to comment out sections of config_batch.xml

### ISSUE THREAD

**Issue by apcraig** [CESM-Development/cime#286]
It's not possible to comment out sections of the config_batch.xml file at the present time due to the parser.  It's handy to be able to comment out sections and test changes.  When I do that, I get errors like

/home/tcraig/cime/cime_config/cesm/machines/config_batch.xml:96: parser error : Comment not terminated 

I tried to comment out a section of config_batch.xml by adding comments around the entire block and on each line and both result in the same problem.  It seems to be confusing the "--" comment tags  with the "--" non-comment strings.  

I assume this could happen in other xml files as well.

**Comment by jedwards4b** [comment]
We think that this may be a LibXML bug, looking into it further.

**Comment by bertinia** [comment]
instead of using



to comment out a block of XML, try

<?ignore .... ?>

The problem is with the SGML specification for comments that is inherited
by XML.

http://www.w3.org/TR/REC-xml/#sec-comments

On Thu, Nov 5, 2015 at 1:32 PM, jedwards4b notifications@github.com wrote:

> We think that this may be a LibXML bug, looking into it further.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CESM-Development/cime/issues/286#issuecomment-154181760
> .

## 

Alice Bertini
NCAR - CSEG Software Engineer

**Comment by jedwards4b** [comment]
I tried this, it works.   Thanks!
