### ISSUE TITLE
Many single-processor tests fail with PIO error: "PNETCDF not enabled in the build"

### ISSUE THREAD

**Issue by billsacks** [CESM-Development/cime#290]
Many single-processor tests – including about half of the tests in the aux_glc test suite – fail with a message like this:

   0: pio_support::pio_die:: myrank=          -1 : ERROR: ionf_mod.F90:         122 : PNETCDF not enabled in the build

SMS_D.f09_g16_gl5.TG.yellowstone_intel gives this traceback:

Image              PC                Routine            Line        Source  
cesm.exe           00000000028243E8  Unknown               Unknown  Unknown
cesm.exe           0000000001FA45BF  pio_support_mp_pi         120  pio_support.F90
cesm.exe           0000000001FA2C39  pio_utils_mp_bad_          97  pio_utils.F90
cesm.exe           00000000021577B9  ionf_mod_mp_creat         122  ionf_mod.F90
cesm.exe           0000000001F9EBF7  piolib_mod_mp_cre        2524  piolib_mod.F90
cesm.exe           000000000077F759  seq_io_mod_mp_seq         203  seq_io_mod.F90
cesm.exe           00000000006F1D36  seq_hist_mod_mp_s         228  seq_hist_mod.F90
cesm.exe           000000000043EA5D  cesm_comp_mod_mp_        3368  cesm_comp_mod.F90
cesm.exe           0000000000447B89  MAIN__                     93  cesm_driver.F90

These failing tests fail from both cesm1_5_beta01 and cesm1_5_beta02. I also notice that every PEA test in the beta02 series failed, and from spot-checking one of these (/glade/scratch/jshollen/PEA_P1_Ld3.T31_g37.X.yellowstone_pgi.GC.cesm15a02fbetapgi) it failed in the same way. 

I am labeling this as critical because I can not run any TG tests or production runs until this is resolved.

**Comment by jedwards4b** [comment]
It appears that this is happening only for TG cases and it's because the
mpilib setting is getting changed after the PIO setting is evaluated.
Instead of trying to unravel that problem I made a change in shr_pio_mod
such that if npes==1 then pnetcdf or netcdf4p are replaced by netcdf in the
typename.   Tested with SMS_D.f09_g16_gl5.TG.yellowstone_intel

Fixed by #291

On Sun, Nov 8, 2015 at 5:58 AM, Bill Sacks notifications@github.com wrote:

> Assigned #290 https://github.com/CESM-Development/cime/issues/290 to
> @jedwards4b https://github.com/jedwards4b.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CESM-Development/cime/issues/290#event-458153189.

## 

Jim Edwards

CESM Software Engineer
National Center for Atmospheric Research
Boulder, CO
