### ISSUE TITLE
create_clone issues 

### ISSUE THREAD

**Issue by jedwards4b** [CESM-Development/cime#293]
When I issue the command
   create_clone -clone $clone -case $case,
the case.run, case.st_archive, and case.lt_archive BSUB lines in $case all retain the name of $clone.  Instead, they should contain the name of $case.

**Comment by sholly** [comment]
Working on this problem for the ensemble scripts, taking..

**Comment by billsacks** [comment]
Another possible issue that someone mentioned to me this morning (I have not confirmed): He says that, if you clone a case from a different sandbox, your clone points to the sandbox used from the original case, rather than the sandbox from which you ran create_clone. He says that it used to do the opposite.

I'm not sure if this is a feature or a bug....

**Comment by jedwards4b** [comment]
It's a bug.  I noticed that as well.

On Mon, Nov 9, 2015 at 7:16 PM, Bill Sacks notifications@github.com wrote:

> Another possible issue that someone mentioned to me this morning (I have
> not confirmed): He says that, if you clone a case from a different sandbox,
> your clone points to the sandbox used from the original case, rather than
> the sandbox from which you ran create_clone. He says that it used to do the
> opposite.
> 
> I'm not sure if this is a feature or a bug....
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CESM-Development/cime/issues/293#issuecomment-155261558
> .

## 

Jim Edwards

CESM Software Engineer
National Center for Atmospheric Research
Boulder, CO

**Comment by mvertens** [comment]
To clarify, I do not think this bug is related to the scripts refactoring -
but has been there all along.

**Comment by sholly** [comment]
Just asking a question of you all since you have been using the model much longer than I have:  
The question is: 

If a user clones a case created from, say, cesm1_5_beta01 using create_clone from cesm1_5_beta02, then the cloned case should take on ALL the configuration information from cesm1_5_beta02?   

Or just the CIMEROOT and SRCROOT?   

Just poking at the can of worms..

**Comment by njn01** [comment]
The bug is fairly new, I think.  I used cesm1_4_beta06 create_clone in August, and the job name in the BSUB command in the *.run script had the correct case name in it.

As for the question about mixing tags when using create_clone, I've never tried it, since I have always considered that to be a very dangerous thing to do.

**Comment by sholly** [comment]
Fixed the original issue with the BSUB case names, create_clone was still trying to remove $CASE.run and so forth instead of case.run.

**Comment by jedwards4b** [comment]
It should take all the configuration from beta02.  But what is there other
than these?

On Tue, Nov 10, 2015 at 10:09 AM, Jay Shollenberger <
notifications@github.com> wrote:

> Just asking a question of you all since you have been using the model much
> longer than I have:
> 
> The question is:
> 
> If a user clones a case created from, say, cesm1_5_beta01 using
> create_clone from cesm1_5_beta02, then the cloned case should take on ALL
> the configuration information from cesm1_5_beta02?
> 
> Or just the CIMEROOT and SRCROOT?
> 
> Just poking at the can of worms..
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CESM-Development/cime/issues/293#issuecomment-155489724
> .

## 

Jim Edwards

CESM Software Engineer
National Center for Atmospheric Research
Boulder, CO

**Comment by mnlevy1981** [comment]
Rewording Jay's question from a couple of comments above mine:

If a user clones a case created from, say, cesm1_5_beta01 using create_clone from cesm1_5_beta02, what should happen?

Possible answers (feel free to add your own if you think my options are incomplete):
- It uses cesm1_5_beta01 settings, like the case being cloned
- It uses cesm1_5_beta02 settings because that is where create_clone lives
- It errors out telling the user to run create_clone from the tag used for the original case

Much like @njn01, I only use create_clone from the tag used to create the original... so erroring out wouldn't affect my workflow at all. That said, I tried to imagine a situation where you create a case in (say) CESM 1.2 and then are curious to see how the same case looks as run from the latest beta tag. Should we allow users to do that? It's very risky thing - POP namelist changes, for example, would be lost because we renamed user_nl_pop2 to user_nl_pop somewhere in the 1_3 or 1_4 beta series. Also, given the way SourceMods work, you run the risk of clobbering a change in the source code. Giving it more thought, we either shouldn't allow clones across tags or we should warn the user that the clone may not behave as expected.

**Comment by billsacks** [comment]
I agree with the feeling of others that cloning a case from one model version in a different model version is a dangerous and unpredictable thing to do. I don't know if there is a "right" way to handle this. (This led me down a chain of thought, thinking about a fundamental change in the operation of create_clone: Rather than copying a bunch of stuff from the source case, it backs out what the user has manually changed in the source case (user_nl_*, changes to the xml files, and SourceMods), creates a user_mods_dir with those changes, and applies it. I'm not sure how to harvest this information, though - particularly the changes to the xml files.)

My understanding of the original issue that was raised to me was that the user was using the same model version, but just in a different sandbox (he was cloning a case that someone else had set up from their sandbox). Then I think the issue became: If he tried to make changes (to source code, etc.) in his sandbox, the clone wouldn't pick them up. I'm not positive about that, though.

**Comment by jedwards4b** [comment]
The changes that we are planning will associate the case with the sandbox
from which create_clone is run.  If that is a different sandbox from the
original case we will include a warning in the output of create_clone to
the effect that cloning from one version to another may lead to unexpected
issues and is not officially supported.

On Tue, Nov 10, 2015 at 11:10 AM, Bill Sacks notifications@github.com
wrote:

> I agree with the feeling of others that cloning a case from one model
> version in a different model version is a dangerous and unpredictable thing
> to do. I don't know if there is a "right" way to handle this. (This led me
> down a chain of thought, thinking about a fundamental change in the
> operation of create_clone: Rather than copying a bunch of stuff from the
> source case, it backs out what the user has manually changed in the source
> case (user_nl_*, changes to the xml files, and SourceMods), creates a
> user_mods_dir with those changes, and applies it. I'm not sure how to
> harvest this information, though - particularly the changes to the xml
> files.)
> 
> My understanding of the original issue that was raised to me was that the
> user was using the same model version, but just in a different sandbox (he
> was cloning a case that someone else had set up from their sandbox). Then I
> think the issue became: If he tried to make changes (to source code, etc.)
> in his sandbox, the clone wouldn't pick them up. I'm not positive about
> that, though.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CESM-Development/cime/issues/293#issuecomment-155517846
> .

## 

Jim Edwards

CESM Software Engineer
National Center for Atmospheric Research
Boulder, CO
