### ISSUE TITLE
SSP test treats ref1 case as the main case

### ISSUE THREAD

**Issue by billsacks** [CESM-Development/cime#56]
For most tests with a ref case, I believe the standard is to have the "bare" case name be the main case, in which comparisons with baselines (etc.) occur. However, this is reversed for the SSP test.

This lack of consistency is a problem for users of the test, and also for tools that post-process test results, such as baseline_gen_comp.

I propose that the SSP test be reworked to switch the meaning of the ref1 case and the "bare" case.

**Comment by mvertens** [comment]
I completely agree. This has confused me in the past and I always have to revisit the logic if there are any issues.

**Comment by jedwards4b** [comment]
To be addressed in python

**Comment by ekluzek** [comment]
@billsacks  and I talked about this and I just need to change the name of the second case so that it's labeled SSP (the new desired name is SPL for spinup Land -- there is a SPO case for the ocean). I want to make sure the second case is the one that is saved and compared because you could do something to screw it up, but still have the first case compare exactly.
