### ISSUE TITLE
Some tests generate file names that exceed max length

### ISSUE THREAD

**Issue by billsacks** [CESM-Development/cime#85]
Some tests with long test names generate component history files with file names that exceed the max length allowed by that component. Instead of causing a failure, components create history files with truncated names. This means that the relevant history files are not compared by the test system.

Here are some examples:

SMS_D_Ld5.T31_g37_gl20.BG1850C5L45BGCIS2.yellowstone_intel.allactive-cism-test_coupling.GC.150730-174900.clm2.h0.0001-01-06-00

SMS_D_Ld5.T31_g37_gl20.BG1850C5L45BGCIS2.yellowstone_intel.allactive-cism-test_coupling.GC.150730-174900.pop.dd.0001-01-02-0

SMS_D_Ld5.T31_g37_gl20.BG1850C5L45BGCIS2.yellowstone_intel.allactive-cism-test_coupling.GC.150730-174900.rtm.h0.0001-01-06-000

The "correct" resolution of this bug is that components should allow longer file names - ideally using allocatable character variables. If that proves to be difficult, then a short-term workaround could be to shorten some long test names, such as by shortening the names of testmod directories.

**Comment by billsacks** [comment]
cc'ing @mvertens @sholly @bandre-ucar @ekluzek @mnlevy1981

**Comment by quantheory** [comment]
Note that as of NAG 6, we should be able to put allocatables in the namelist for all compilers. (Might want to double-check that, though.) This will probably require two namelist groups to read, though, one to specify the string length so that you can allocate, and the other to actually read in the string into the allocated variable.

Also, if you wanted to CC the model liaisons, @brian-eaton is now on GitHub too.

**Comment by billsacks** [comment]
Thanks, @quantheory : I remembered there being some issue with this before, and couldn't remember what, so thanks for the reminder. I didn't include @brian-eaton because, at least for the test where I found the issue, CAM could handle long-enough history file names. I guess that an even longer case name would cause it problems, but for now CLM, POP and RTM seem to be the main culprits.

**Comment by mnlevy1981** [comment]
I made a new POP tag that increases the default string length from 256 to 384 (POP tag 20150810, on the plans page from cesm1_4_alpha07b) and the extra 128 characters fixed the issue with the pop.dd files. This is a pretty kludgy fix - a better option would be to switch from `char_len` to `char_len_long` (which is 512) for strings that contain file names because then we could leave `char_len` set to 256; I left a comment to that effect in kinds_mod.F90 and POP_KindsMod.F90 so that when future-me has more time to spend on the issue I'll remember to apply a more proper fix.

**Comment by billsacks** [comment]
@fischer-ncar says that the main remaining issue seems to be RTM.

@apcraig suggests that we figure out the current max allowed length. Then we can test for that in the scripts.

**Comment by ekluzek** [comment]
​The latest version of MOSART and RTM has this fixed. They are scheduled to
come in the beta tag after the current one being worked on.

I think the current limit might be in CLM which I think is 199 characters
right now as we had trouble moving it to 255.

_Erik Kluzek, (CGD at NCAR)_

_National Center for Atmospheric Research_

*Boulder CO, *

_(off) (303)497-1326 (fax) (303)497-1348_

_(skype) ekluzek    (cell) (303)859-0183_

_Pronouns: he/his/him_

_------------------ Home page ------------------------_
- ```
       http://www.cgd.ucar.edu/~erik <http://www.cgd.ucar.edu/~erik>*
  ```
- ```
       https://staff.ucar.edu/users/erik
  ```
  
  https://staff.ucar.edu/users/erik*

_!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!_

**Comment by billsacks** [comment]
Closing... making this part of https://github.com/ESMCI/cime/issues/853
